  
# deploy.yml
name: release
on:
  push:
    tags:
      - 'staging*'
      - 'develop*'
      - 'staging*'
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      sha: $GITHUB_SHA
    steps:
#     - uses: actions/checkout@v2.3.4
#       with:
#         ref: env.sha
#     - uses: actions/setup-node@v1
#       with:
#         node-version: 15
#     - name: install
#       run: ls
    - name: install
      run: |
        echo $GITHUB_SHA
        echo env.sha
#       env:
#           FIRST_NAME: Mona
#           middle_name: The
#           Last_Name: Octocat
