  
# deploy.yml
name: release
on:
  push:
    tags:
      - 'staging*'
      - 'develop*'
      - 'staging*'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2.3.4
      with:
        ref: ${{ github.ref }}
#     - uses: actions/setup-node@v2.1.4
#       with:
#         node-version: 15
#     - name: install
#       run: |
#           npm install
#           npm build
    - name: Deploy
      run: echo ${{ github.ref }}
    - uses: fifsky/ssh-action@v0.0.5
      with:
        command: |
          cd /root 
          ./ci.sh ${{ github.ref }}
        host: ${{ secrets.HOST }}
        key: ${{ secrets.PRIVATE_KEY}}
