  
# deploy.yml
name: release
on:
  push:
    tags:
      - 'staging*'
      - 'develop*'
      - 'staging*'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2.3.4
      with:
        ref: $GITHUB_SHA
    - uses: actions/setup-node@v1
      with:
        node-version: 15
    - name: install
    - run: ls
    - run: $GITHUB_SHA
