  
# deploy.yml
name: release
on:
  push:
    tags:
      - 'staging*'
      - 'develop*'
      - 'staging*'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
#     - uses: actions/checkout@v2.3.4
#       with:
#         ref: env.sha
#     - uses: actions/setup-node@v1
#       with:
#         node-version: 15
#     - name: install
#       run: ls
    - name: install
      env:
        GITHUB_CONTEXT: ${{ toJSON(github) }}
      run: |
        echo $GITHUB_SHA
        echo $GITHUB_CONTEXT.ref
        echo $GITHUB_CONTEXT
#       env:
#           FIRST_NAME: Mona
#           middle_name: The
#           Last_Name: Octocat
