
# deploy.yml
name: release
on:
  push:
    tags:
      - 'staging*'
      - 'develop*'
      - 'staging*'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    #   ref: ${{ github.ref }}- uses: actions/checkout@v2.3.4
    #   ref: ${{ github.ref }}  with:
    #   ref: ${{ github.ref }}
    #     - uses: actions/setup-node@v2.1.4
    #       with:
    #         node-version: 15
    #     - name: install
    #       run: |
    #           npm install
    #           npm build
      - uses: garygrossgarten/github-action-ssh@release # 使用ssh链接服务器
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          privateKey: ${{ secrets.PRIVATE_KEY}}
          port: ${{ secrets.POTR}}
          command: |
            cd /root
            ./ci.sh ${{ github.ref }}
